name: Accessibility Audits

on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Accessibility Scan
        uses: mattorb/lumberjack@github-action
        with:
          url: "https://mattorb.com"